/**
 * Turn a tier's accepted candidates into canonical SQL rows.
 *
 *   pnpm --filter @whilom/ingestion scale:seed -- --tier 5000
 *
 * Writes `scale-seed-<tier>.sql`. The query lane loads this into an ephemeral
 * Supabase in CI and measures the read paths the product actually uses, so the
 * rows carry real names, real place types and real Ordnance-Survey-derived
 * coordinates rather than generated noise. Measuring a spatial index against
 * uniformly random points would flatter it: heritage is clustered, and the
 * clustering is what makes a bounded-area query expensive.
 *
 * Only records the matcher accepted as new canonical places are emitted. Rows
 * awaiting review are not canonical and would not be queryable.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { HistoricEnglandNhleAdapter } from '../sources/historic-england/nhle-adapter';
import { normaliseNhleRecord } from '../transforms/normalise-nhle';
import { runIngestion } from '../pipeline/run';
import { MatchOutcome } from '../pipeline/candidate';
import { buildTierFixture, isTierSize } from './tier';

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Stable, collision-free slug from the source record id. */
function slugFor(name: string, sourceRecordId: string): string {
  const base = name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return `${base || 'place'}-${sourceRecordId}`;
}

export async function buildSeed(tier: number): Promise<string> {
  const fixture = buildTierFixture(tier);
  const report = await runIngestion({
    importRunId: `scale-seed-${tier}`,
    sources: [
      {
        adapter: new HistoricEnglandNhleAdapter({ kind: 'file', path: fixture.path }),
        normalise: normaliseNhleRecord,
      },
    ],
  });

  const rows: string[] = [];
  for (const decided of report.decided) {
    if (decided.decision.outcome !== MatchOutcome.NewCanonical) continue;
    const c = decided.candidate;
    rows.push(
      `(${[
        quote(slugFor(c.name, c.provenance.sourceRecordId)),
        quote(c.name),
        `${quote(c.placeType)}::public.place_type`,
        c.town ? quote(c.town) : 'null',
        c.county ? quote(c.county) : 'null',
        c.postcode ? quote(c.postcode) : 'null',
        `extensions.st_setsrid(extensions.st_makepoint(${c.location.lng}, ${c.location.lat}), 4326)::extensions.geography`,
        String(Math.round(c.locationAccuracyMeters)),
      ].join(', ')})`,
    );
  }

  const header = `-- Scale seed, tier ${tier}. Generated by ingestion/scale/db-seed.ts.
-- ${rows.length} canonical places derived from real National Heritage List for
-- England records (OGL v3.0). Do not edit by hand.
`;

  // Chunked so one statement does not carry 5,000 tuples.
  const chunks: string[] = [];
  const CHUNK = 500;
  for (let i = 0; i < rows.length; i += CHUNK) {
    chunks.push(
      `insert into public.places (slug, name, place_type, town, county, postcode, location, location_accuracy_m) values\n${rows
        .slice(i, i + CHUNK)
        .join(',\n')};`,
    );
  }

  return `${header}\n${chunks.join('\n\n')}\n\nanalyze public.places;\n`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const index = process.argv.indexOf('--tier');
  const tier = Number(index >= 0 ? process.argv[index + 1] : NaN);
  if (!isTierSize(tier)) {
    console.error('--tier must be one of 1000, 2500, 5000, 10000, 25000');
    process.exitCode = 1;
  } else {
    buildSeed(tier)
      .then((sql) => {
        const out = resolve(process.cwd(), `scale-seed-${tier}.sql`);
        writeFileSync(out, sql);
        console.log(`wrote ${out} (${sql.split('\n').length} lines)`);
      })
      .catch((error: unknown) => {
        console.error(error);
        process.exitCode = 1;
      });
  }
}
