/**
 * The decision oracle.
 *
 * A frozen, machine-readable record of what the corrected exhaustive matcher
 * decided about every source record in a tier. Nothing here is hand-authored:
 * the expectations are generated by running the real pipeline, which is the
 * only way an equivalence claim means anything.
 *
 * Its purpose is narrow and important. Batch 6 established, by hand audit, that
 * all 11 automatic merges at 5,000 records are correct. Bounding candidate
 * discovery must not disturb a single one of those decisions, and "the numbers
 * still look about right" is not a proof. This file makes the claim checkable:
 *
 *   pnpm --filter @whilom/ingestion scale:oracle -- --tier 5000
 *   pnpm --filter @whilom/ingestion scale:equivalence -- --tier 5000
 */

import { createHash } from 'node:crypto';
import type { RunReport } from '../pipeline/run';
import type { DecidedCandidate } from '../pipeline/run';
import { MatchOutcome } from '../pipeline/candidate';

/** One record's fate, in a form that is stable across runs and strategies. */
export interface OracleEntry {
  /**
   * Position in the run's processing order, and the join key for comparison.
   *
   * NOT the source record id, which is not unique: the NHLE service returns one
   * row per geometry part, so a multi-part World Heritage Site like Studley
   * Royal arrives twice under a single list entry. Keying a comparison by that
   * id silently collapses the pair and then reports the survivor as a
   * difference. Both strategies read the same fixture in the same order, so
   * ordinal N is the same input record in both.
   */
  ordinal: number;
  /** The source's own identifier. Checked, but not unique — see `ordinal`. */
  sourceRecordId: string;
  sourceId: string;
  name: string;
  placeType: string;
  /** NEW_CANONICAL / MATCH_CONFIDENT / MATCH_REVIEW / CONFLICT_REVIEW / REJECT_INVALID. */
  decision: MatchOutcome;
  /** The source record this was matched to, when it matched something. */
  matchedSourceRecordId: string | null;
  /** True when the decision routes the record to a human. */
  requiresReview: boolean;
  /** Field-level disagreements the matcher raised, sorted for stability. */
  conflictFields: string[];
  /** Cross-source comparison outcome, when one was performed. */
  comparisonOutcome: string | null;
  confidence: number;
  /**
   * The matcher's own explanation. Compared as well as the decision, because
   * two strategies reaching the same outcome for different stated reasons is
   * itself a finding worth surfacing.
   */
  rationale: string;
}

export interface Oracle {
  tier: number;
  /** How candidates were discovered for this run. */
  candidateMode: string;
  generatedAt: string;
  sourceRows: number;
  /** Counts by decision, for a fast eyeball before the entry-level diff. */
  summary: Record<string, number>;
  /** Digest of the decision-bearing fields only; see `digestOf`. */
  digest: string;
  entries: OracleEntry[];
}

function requiresReview(outcome: MatchOutcome): boolean {
  return outcome === MatchOutcome.MatchReview || outcome === MatchOutcome.ConflictReview;
}

function entryOf(decided: DecidedCandidate, ordinal: number): OracleEntry {
  return {
    ordinal,
    sourceRecordId: decided.candidate.provenance.sourceRecordId,
    sourceId: decided.candidate.provenance.sourceId,
    name: decided.candidate.name,
    placeType: decided.candidate.placeType,
    decision: decided.decision.outcome,
    matchedSourceRecordId: decided.matchedSourceRecordId ?? null,
    requiresReview: requiresReview(decided.decision.outcome),
    conflictFields: decided.decision.conflicts.map((c) => c.field).sort(),
    comparisonOutcome: decided.comparison?.outcome ?? null,
    confidence: decided.decision.confidence,
    rationale: decided.decision.rationale,
  };
}

/**
 * Separators chosen so that no field value can forge a boundary. Written as
 * character codes rather than literals: a raw control byte in a source file is
 * invisible in review and has bitten this repository before.
 */
const FIELD_SEPARATOR = String.fromCharCode(31);
const RECORD_SEPARATOR = String.fromCharCode(30);

/**
 * A digest over the decision-bearing fields, so an equivalence check can fail
 * fast and a result file can be compared at a glance.
 *
 * Deliberately excludes timings, comparison counts and anything else that a
 * different candidate strategy is *expected* to change. Including them would
 * make the digest differ for exactly the reason the optimisation exists.
 */
export function digestOf(entries: readonly OracleEntry[]): string {
  const hash = createHash('sha256');
  for (const entry of entries) {
    hash.update(
      [
        String(entry.ordinal),
        entry.sourceRecordId,
        entry.decision,
        entry.matchedSourceRecordId ?? '-',
        String(entry.requiresReview),
        entry.conflictFields.join('+'),
        entry.comparisonOutcome ?? '-',
        entry.confidence.toFixed(6),
      ].join(FIELD_SEPARATOR),
    );
    hash.update(RECORD_SEPARATOR);
  }
  return hash.digest('hex');
}

export function buildOracle(tier: number, candidateMode: string, report: RunReport): Oracle {
  // Kept in processing order and keyed by ordinal. Sorting by source record id
  // would be no more stable — that id is not unique — and would obscure which
  // of two identically-numbered rows is which.
  const entries = report.decided.map((decided, ordinal) => entryOf(decided, ordinal));

  const summary: Record<string, number> = {};
  for (const entry of entries) summary[entry.decision] = (summary[entry.decision] ?? 0) + 1;
  summary['REQUIRES_REVIEW'] = entries.filter((e) => e.requiresReview).length;

  return {
    tier,
    candidateMode,
    generatedAt: new Date().toISOString(),
    sourceRows: report.sourceRows,
    summary,
    digest: digestOf(entries),
    entries,
  };
}

/** One record on which two strategies disagreed. */
export interface DecisionDifference {
  sourceRecordId: string;
  name: string;
  field: string;
  exhaustive: string;
  bounded: string;
}

/**
 * Compare two oracles record by record.
 *
 * Reports every differing field rather than stopping at the first, because when
 * a pruning bug does appear the shape of the disagreement is what identifies
 * it — a handful of lost identifier matches looks nothing like a systematic
 * spatial off-by-one.
 */
export function compareOracles(exhaustive: Oracle, bounded: Oracle): DecisionDifference[] {
  const differences: DecisionDifference[] = [];
  const byOrdinal = new Map(bounded.entries.map((e) => [e.ordinal, e]));

  for (const left of exhaustive.entries) {
    const right = byOrdinal.get(left.ordinal);
    if (!right) {
      differences.push({
        sourceRecordId: left.sourceRecordId,
        name: left.name,
        field: 'presence',
        exhaustive: 'decided',
        bounded: 'absent',
      });
      continue;
    }
    byOrdinal.delete(left.ordinal);

    const check = (field: string, a: string, b: string): void => {
      if (a !== b) {
        differences.push({ sourceRecordId: left.sourceRecordId, name: left.name, field, exhaustive: a, bounded: b });
      }
    };

    // The id is checked rather than assumed: if the two runs ever processed
    // different records at the same ordinal, every later comparison would be
    // meaningless and this is what says so.
    check('sourceRecordId', left.sourceRecordId, right.sourceRecordId);
    check('decision', left.decision, right.decision);
    check('matchedSourceRecordId', left.matchedSourceRecordId ?? '-', right.matchedSourceRecordId ?? '-');
    check('requiresReview', String(left.requiresReview), String(right.requiresReview));
    check('conflictFields', left.conflictFields.join('+'), right.conflictFields.join('+'));
    check('comparisonOutcome', left.comparisonOutcome ?? '-', right.comparisonOutcome ?? '-');
    check('confidence', left.confidence.toFixed(6), right.confidence.toFixed(6));
    check('rationale', left.rationale, right.rationale);
  }

  for (const orphan of byOrdinal.values()) {
    differences.push({
      sourceRecordId: orphan.sourceRecordId,
      name: orphan.name,
      field: 'presence',
      exhaustive: 'absent',
      bounded: 'decided',
    });
  }

  return differences;
}
